### ISSUE TITLE
Add Fitur Anti Tab tanpa install extension atau aplikasi tambahan

### ISSUE THREAD

**Issue by taramaxi78** [shellrean-dev/exo-cbt-4-rosetta-issue#2]
fitur dalam exo 3,17 sudah bagus tinggal di tambahkan ke dalam fitur rosseta, karena jika di pakai ujian sekolah yg siswanya memakai laptop sendiri tidak merepotkan tim ITnya

**Comment by shellrean** [comment]
ini kembali lagi ke keinginan sekolah. tujuan penggunaan fitur anti switch tab adalah untuk mengurangi kecurangan. jika sekolah memang mau mengantisipasi kecurangan sudah seharusnya memberikan effort yang lebih.
fitur tab dipindahkan ke extensi karena lebih baik dalam menghadapi lebih banyak kasus.

jika tim IT tidak ingin direpotkan, akan lebih baik minta tim IT lain atau hire source lagi.
