### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by indrstwn** [shellrean-dev/exo-cbt-4-rosetta-issue#3]
**Jelaskan bugnya**
Deskripsi yang jelas dan ringkas tentang apa itu bug.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Version [e.g. 4.1.1]

**Additional context**
gambar mulai dari logo sekolah sampai gambar di naskah soal tidak tampil di server ataupun client

**Comment by shellrean** [comment]
Ini dikarenakan SERVER_ASSET_URL tidak benar
