### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by alvinazhar** [shellrean-dev/exo-cbt-4-rosetta-issue#4]
**Jelaskan bugnya**
Deskripsi yang jelas dan ringkas tentang apa itu bug.

**To Reproduce**

**Expected behavior**

**Screenshots**
![ERROR](https://github.com/user-attachments/assets/65fe764a-a253-4391-bd37-5b16f949c4ee)

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]

 - Version [e.g. 4.1.1]

**Additional context**

**Comment by shellrean** [comment]
Issue closed, ini karena salah setting php, wajib php versi 7.4
